name: flutter_mdi_icons
description: Material Design Icons made by Community for Flutter Project.
version: 0.1.1
homepage: https://github.com/arhamcode/flutter_mdi_icons

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.1.0

flutter:
  fonts:
    - family: MaterialDesignIcons
      fonts:
        - asset: lib/font/materialdesignicons-webfont.ttf
